# 请将该 Dockerfile 放在前端项目的根目录下
FROM node:lts-slim
LABEL authors="Charlott2"\
      description="构建用于运行 Web 前端项目的 Node.js 镜像"

# 服务端口
ARG SERVER_PORT=5173

WORKDIR /app
VOLUME [ "/app" ]
RUN if [! -f /app/node_modules ]; then npm install; fi

EXPOSE ${SERVER_PORT}
