# 请将该 Dockerfile 放在后端项目的根目录下
FROM tomcat:10
LABEL authors="Oddy"\
      description="构建用于运行 Java Web 项目的 Tomcat 镜像"

# 工件名称
ARG ARTIFACT_NAME="default-artifact-name"
# 工件版本
ARG ARTIFACT_VERSION="0.0.1-SNAPSHOT"
# 服务端口
ARG SERVER_PORT=8080

WORKDIR /app
COPY target/${ARTIFACT_NAME}-${ARTIFACT_VERSION}.war /usr/local/tomcat/webapps/

EXPOSE ${SERVER_PORT}

ENTRYPOINT ["catalina.sh", "run"]
