# 请将该 Dockerfile 放在后端项目的根目录下
FROM tomcat:10-jdk21-temurin
LABEL authors="Oddy"

WORKDIR /app
ARG ARTIFACT_NAME
COPY target/${ARTIFACT_NAME} /usr/local/tomcat/webapps/
# 开放端口默认为 8080，根据情况修改
EXPOSE 8080

ENTRYPOINT ["catalina.sh", "run"]
