FROM tomcat:10-jdk21-temurin
LABEL authors="Oddy"

# 后端项目构建出的的 war 包的相对路径，根据情况修改，这里以 target/yourprojname-*.war 为例
ADD target/yourprojname-*.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]
