FROM eclipse-temurin:17-jdk
LABEL authors="Oddy"

# 后端项目构建出的的 jar 包的相对路径，根据情况修改，这里以 target/yourjarfile.jar 为例
ADD target/yourjarfile.jar /home/app.jar
EXPOSE 8080
CMD ["java", "-jar", "/home/app.jar"]
